#!/usr/bin/env python3
"""Smoke-test fast-fork epoch rollback against an installed build."""

from __future__ import annotations

import argparse
import os
import shutil
import socket
import subprocess
import sys
import tempfile
import time
from pathlib import Path


FAST_SETTINGS = {
    "listen_addresses": "",
    "fsync": "off",
    "synchronous_commit": "off",
    "full_page_writes": "off",
    "wal_level": "minimal",
    "archive_mode": "off",
    "max_wal_senders": "0",
    "max_replication_slots": "0",
    "autovacuum": "off",
    "track_counts": "off",
    "jit": "off",
}


SETUP_SQL = r"""
\set ON_ERROR_STOP on
CREATE TABLE epoch_parent(id int PRIMARY KEY, val text NOT NULL, bucket int NOT NULL);
CREATE INDEX epoch_parent_bucket_idx ON epoch_parent(bucket, id);
CREATE TABLE epoch_child(
    id int PRIMARY KEY,
    parent_id int NOT NULL REFERENCES epoch_parent(id),
    amount int NOT NULL
);
CREATE INDEX epoch_child_parent_amount_idx ON epoch_child(parent_id, amount);
CREATE TABLE epoch_batch(
    id int PRIMARY KEY,
    note text NOT NULL
);
CREATE TABLE epoch_claim(
    id int PRIMARY KEY,
    batch_id int NOT NULL REFERENCES epoch_batch(id),
    payload text NOT NULL
);
CREATE INDEX epoch_claim_batch_idx ON epoch_claim(batch_id, id);
CREATE TABLE epoch_generated_batch(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note text NOT NULL
);
CREATE TABLE epoch_generated_claim(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id int NOT NULL REFERENCES epoch_generated_batch(id),
    payload text NOT NULL
);
CREATE INDEX epoch_generated_claim_batch_idx ON epoch_generated_claim(batch_id, id);
INSERT INTO epoch_parent
SELECT g, 'base-' || g::text, g % 4 FROM generate_series(1, 25) AS g;
INSERT INTO epoch_child
SELECT g, ((g - 1) % 25) + 1, g % 10 FROM generate_series(1, 80) AS g;
SELECT pg_fastfork_snapshot('fixture');
"""


CAPTURE_SQL = r"""
\set ON_ERROR_STOP on
SELECT pg_fastfork_snapshot('fixture');
"""


DML_SQL = r"""
\set ON_ERROR_STOP on
SELECT pg_fastfork_restore('fixture');
BEGIN;
SELECT pg_fastfork_epoch_begin();
SELECT pg_fastfork_epoch_status();
UPDATE epoch_parent SET val = 'changed' WHERE id = 1;
DELETE FROM epoch_child WHERE parent_id = 1;
INSERT INTO epoch_child VALUES (1000, 2, 42);
SAVEPOINT s;
INSERT INTO epoch_child VALUES (1001, 3, 43);
ROLLBACK TO s;
SELECT 1 / CASE WHEN (SELECT val FROM epoch_parent WHERE id = 1) = 'changed'
           THEN 1 ELSE 0 END;
SELECT 1 / CASE WHEN NOT EXISTS (SELECT 1 FROM epoch_child WHERE id = 1001)
           THEN 1 ELSE 0 END;
ROLLBACK;
DO $$
BEGIN
  IF (SELECT val FROM epoch_parent WHERE id = 1) <> 'base-1' THEN
    RAISE EXCEPTION 'epoch rollback leaked heap update';
  END IF;

  IF (SELECT count(*) FROM epoch_child WHERE parent_id = 1) <> 4 THEN
    RAISE EXCEPTION 'epoch rollback leaked child delete';
  END IF;

  IF EXISTS (SELECT 1 FROM epoch_child WHERE id IN (1000, 1001)) THEN
    RAISE EXCEPTION 'epoch rollback leaked inserted rows';
  END IF;
END $$;
SET enable_seqscan = off;
SELECT val FROM epoch_parent WHERE bucket = 1 AND id = 5;
"""


SESSION_SQL = r"""
\set ON_ERROR_STOP on
SELECT pg_fastfork_restore('fixture');
SELECT pg_fastfork_epoch_session_begin();
BEGIN;
UPDATE epoch_parent SET val = 'session-changed' WHERE id = 1;
INSERT INTO epoch_child VALUES (1500, 2, 45);
COMMIT;
SELECT 1 / CASE WHEN (SELECT val FROM epoch_parent WHERE id = 1) = 'session-changed'
           THEN 1 ELSE 0 END;
SELECT pg_fastfork_epoch_leave();
DO $$
BEGIN
  IF (SELECT val FROM epoch_parent WHERE id = 1) <> 'base-1' THEN
    RAISE EXCEPTION 'session epoch leave leaked heap update';
  END IF;

  IF EXISTS (SELECT 1 FROM epoch_child WHERE id = 1500) THEN
    RAISE EXCEPTION 'session epoch leave leaked inserted row';
  END IF;
END $$;
"""


NAMED_SQL = r"""
\set ON_ERROR_STOP on
SELECT pg_fastfork_restore('fixture');
SELECT pg_fastfork_epoch_start('named-test', 'fixture');
SELECT pg_fastfork_epoch_join('named-test');
BEGIN;
UPDATE epoch_parent SET val = 'named-changed' WHERE id = 1;
INSERT INTO epoch_child VALUES (1600, 2, 46);
COMMIT;
SELECT 1 / CASE WHEN (SELECT val FROM epoch_parent WHERE id = 1) = 'named-changed'
           THEN 1 ELSE 0 END;
SELECT pg_fastfork_epoch_leave();
SELECT pg_fastfork_epoch_finish('named-test');
DO $$
BEGIN
  IF (SELECT val FROM epoch_parent WHERE id = 1) <> 'base-1' THEN
    RAISE EXCEPTION 'named epoch finish leaked heap update';
  END IF;

  IF EXISTS (SELECT 1 FROM epoch_child WHERE id = 1600) THEN
    RAISE EXCEPTION 'named epoch finish leaked inserted row';
  END IF;
END $$;
"""


COMMIT_SQL = r"""
\set ON_ERROR_STOP on
SELECT pg_fastfork_restore('fixture');
BEGIN;
SELECT pg_fastfork_epoch_begin();
UPDATE epoch_parent SET val = 'commit-leak' WHERE id = 1;
COMMIT;
"""


DDL_SQL = r"""
\set ON_ERROR_STOP on
SELECT pg_fastfork_restore('fixture');
BEGIN;
SELECT pg_fastfork_epoch_begin();
CREATE TABLE epoch_ddl_parent(
    id int PRIMARY KEY,
    parent_id int NOT NULL REFERENCES epoch_parent(id),
    amount int NOT NULL
);
CREATE INDEX epoch_ddl_parent_amount_idx ON epoch_ddl_parent(amount, id);
INSERT INTO epoch_ddl_parent VALUES (1, 1, 10), (2, 2, 20);
SAVEPOINT ddl_savepoint;
CREATE TABLE epoch_ddl_child(id int PRIMARY KEY);
INSERT INTO epoch_ddl_child VALUES (1);
ROLLBACK TO ddl_savepoint;
SELECT 1 / CASE WHEN to_regclass('epoch_ddl_child') IS NULL
           THEN 1 ELSE 0 END;
SELECT count(*) FROM epoch_ddl_parent WHERE amount >= 10;
ROLLBACK;
SELECT 1 / CASE WHEN to_regclass('epoch_ddl_parent') IS NULL
           THEN 1 ELSE 0 END;
SELECT 1 / CASE WHEN to_regclass('epoch_ddl_parent_amount_idx') IS NULL
           THEN 1 ELSE 0 END;
"""


PARALLEL_CONN1_SQL = """
BEGIN;
SELECT pg_fastfork_epoch_begin();
INSERT INTO epoch_child VALUES (2000, 2, 50);
SELECT pg_sleep(1.0);
SELECT 1 / CASE WHEN EXISTS (SELECT 1 FROM epoch_child WHERE id = 2000)
           THEN 1 ELSE 0 END;
ROLLBACK;
"""


PARALLEL_CONN2_SQL = """
BEGIN;
SELECT pg_fastfork_epoch_begin();
INSERT INTO epoch_child VALUES (2001, 3, 51);
SELECT pg_fastfork_epoch_status();
ROLLBACK;
"""


PARALLEL_VERIFY_SQL = r"""
\set ON_ERROR_STOP on
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM epoch_child WHERE id IN (2000, 2001)) THEN
    RAISE EXCEPTION 'parallel epoch rollback leaked inserted rows';
  END IF;
END $$;
"""


PARALLEL_NAMED_SETUP_SQL = r"""
\set ON_ERROR_STOP on
SELECT pg_fastfork_restore('fixture');
SELECT pg_fastfork_epoch_start('named-a', 'fixture');
SELECT pg_fastfork_epoch_start('named-b', 'fixture');
"""


PARALLEL_NAMED_CONN1_SQL = """
SELECT pg_fastfork_epoch_join('named-a');
BEGIN;
INSERT INTO epoch_child
SELECT 300000 + g, 2, g % 100
FROM generate_series(1, 6000) AS g;
SELECT pg_sleep(1.0);
COMMIT;
SELECT 1 / CASE WHEN (SELECT count(*) FROM epoch_child
                      WHERE id BETWEEN 300001 AND 306000) = 6000
           THEN 1 ELSE 0 END;
SELECT pg_fastfork_epoch_leave();
"""


PARALLEL_NAMED_CONN2_SQL = """
SELECT pg_fastfork_epoch_join('named-b');
BEGIN;
INSERT INTO epoch_child
SELECT 300000 + g, 3, g % 100
FROM generate_series(1, 6000) AS g;
COMMIT;
SELECT 1 / CASE WHEN (SELECT count(*) FROM epoch_child
                      WHERE id BETWEEN 300001 AND 306000) = 6000
           THEN 1 ELSE 0 END;
SELECT pg_fastfork_epoch_leave();
"""


PARALLEL_NAMED_FINISH_SQL = r"""
\set ON_ERROR_STOP on
SELECT pg_fastfork_epoch_finish('named-a');
SELECT pg_fastfork_epoch_finish('named-b');
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM epoch_child WHERE id BETWEEN 300001 AND 306000) THEN
    RAISE EXCEPTION 'parallel named epoch finish leaked inserted row';
  END IF;
END $$;
"""


PARALLEL_NAMED_ACTIVE_CONN1_SQL = """
SELECT pg_fastfork_epoch_join('active-a');
SET enable_seqscan = off;
BEGIN;
INSERT INTO epoch_child
SELECT 500000 + g, 2, g % 100
FROM generate_series(1, 6000) AS g;
SELECT pg_sleep(1.0);
SELECT 1 / CASE WHEN (SELECT count(*) FROM epoch_child
                      WHERE id BETWEEN 500001 AND 506000) = 6000
           THEN 1 ELSE 0 END;
COMMIT;
SELECT pg_fastfork_epoch_leave();
"""


PARALLEL_NAMED_ACTIVE_CONN2_SQL = """
SELECT pg_fastfork_epoch_join('active-b');
SET enable_seqscan = off;
BEGIN;
INSERT INTO epoch_child
SELECT 500000 + g, 3, g % 100
FROM generate_series(1, 6000) AS g;
COMMIT;
SELECT 1 / CASE WHEN (SELECT count(*) FROM epoch_child
                      WHERE id BETWEEN 500001 AND 506000) = 6000
           THEN 1 ELSE 0 END;
SELECT pg_fastfork_epoch_leave();
"""


PARALLEL_NAMED_ACTIVE_FINISH_SQL = r"""
\set ON_ERROR_STOP on
SELECT pg_fastfork_epoch_finish('active-b');
SELECT 1 / CASE
    WHEN substring(pg_fastfork_epoch_status() from 'arena_free_pages=([0-9]+)')::int > 0
    THEN 1 ELSE 0 END;
"""


PARALLEL_NAMED_ACTIVE_FINAL_SQL = r"""
\set ON_ERROR_STOP on
SELECT pg_fastfork_epoch_finish('active-a');
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM epoch_child WHERE id BETWEEN 500001 AND 506000) THEN
    RAISE EXCEPTION 'active parallel named epoch finish leaked inserted row';
  END IF;
END $$;
"""


NAMED_SESSION_VISIBILITY_SETUP_SQL = r"""
\set ON_ERROR_STOP on
SELECT pg_fastfork_restore('fixture');
SELECT pg_fastfork_epoch_start('visibility', 'fixture');
"""


NAMED_SESSION_VISIBILITY_READER_SQL = """
SELECT pg_fastfork_epoch_join('visibility');
SET enable_seqscan = off;
SELECT 1 / CASE WHEN (SELECT count(*) FROM epoch_claim WHERE batch_id = 7001) = 0
           THEN 1 ELSE 0 END;
SELECT 1 / CASE WHEN (SELECT count(*) FROM epoch_generated_claim WHERE batch_id = 1) = 0
           THEN 1 ELSE 0 END;
SELECT pg_sleep(1.0);
SELECT pg_fastfork_epoch_join('visibility');
SELECT 1 / CASE WHEN (SELECT count(*) FROM epoch_claim WHERE batch_id = 7001) = 2
           THEN 1 ELSE 0 END;
SELECT 1 / CASE WHEN (SELECT count(*) FROM epoch_generated_claim WHERE batch_id = 1) = 2
           THEN 1 ELSE 0 END;
SELECT pg_fastfork_epoch_leave();
"""


NAMED_SESSION_VISIBILITY_WRITER_SQL = """
SELECT pg_fastfork_epoch_join('visibility');
BEGIN;
INSERT INTO epoch_batch VALUES (7001, 'generated');
INSERT INTO epoch_claim VALUES
    (700101, 7001, 'first'),
    (700102, 7001, 'second');
WITH batch AS (
    INSERT INTO epoch_generated_batch(note) VALUES ('generated')
    RETURNING id
)
INSERT INTO epoch_generated_claim(batch_id, payload)
SELECT batch.id, payload
FROM batch
CROSS JOIN (VALUES ('first'), ('second')) AS claims(payload);
COMMIT;
SELECT pg_sleep(1.0);
SELECT pg_fastfork_epoch_leave();
"""


NAMED_SESSION_VISIBILITY_FINISH_SQL = r"""
\set ON_ERROR_STOP on
SELECT pg_fastfork_epoch_finish('visibility');
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM epoch_claim WHERE batch_id = 7001) THEN
    RAISE EXCEPTION 'named epoch finish leaked committed child rows';
  END IF;

  IF EXISTS (SELECT 1 FROM epoch_generated_claim WHERE batch_id = 1) THEN
    RAISE EXCEPTION 'named epoch finish leaked committed generated child rows';
  END IF;
END $$;
"""


REUSED_BACKEND_NAMED_SQL = r"""
\set ON_ERROR_STOP on
SELECT pg_fastfork_restore('fixture');
SELECT pg_fastfork_epoch_start('reuse-a', 'fixture');
SELECT pg_fastfork_epoch_join('reuse-a');
BEGIN;
INSERT INTO epoch_child
SELECT 400000 + g, 2, g % 100
FROM generate_series(1, 6000) AS g;
SELECT 1 / CASE WHEN (SELECT count(*) FROM epoch_child
                      WHERE id BETWEEN 400001 AND 406000) = 6000
           THEN 1 ELSE 0 END;
ROLLBACK;
SELECT pg_fastfork_epoch_leave();
SELECT pg_fastfork_epoch_start('reuse-b', 'fixture');
SELECT pg_fastfork_epoch_join('reuse-b');
BEGIN;
INSERT INTO epoch_child
SELECT 400000 + g, 3, g % 100
FROM generate_series(1, 6000) AS g;
SELECT 1 / CASE WHEN (SELECT count(*) FROM epoch_child
                      WHERE id BETWEEN 400001 AND 406000) = 6000
           THEN 1 ELSE 0 END;
ROLLBACK;
SELECT pg_fastfork_epoch_leave();
SELECT pg_fastfork_epoch_finish('reuse-a');
SELECT pg_fastfork_epoch_finish('reuse-b');
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM epoch_child WHERE id BETWEEN 400001 AND 406000) THEN
    RAISE EXCEPTION 'reused backend named epoch leaked inserted row';
  END IF;
END $$;
"""


UNSUPPORTED_DDL_SQL = r"""
\set ON_ERROR_STOP on
SELECT pg_fastfork_restore('fixture');
BEGIN;
SELECT pg_fastfork_epoch_begin();
CREATE SCHEMA epoch_bad;
ROLLBACK;
"""


PREPARE_SQL = r"""
\set ON_ERROR_STOP on
SELECT pg_fastfork_restore('fixture');
BEGIN;
SELECT pg_fastfork_epoch_begin();
PREPARE TRANSACTION 'epoch_bad';
"""


BROKEN_NAMED_CONN_SQL = """
SELECT pg_fastfork_epoch_join('broken-cleanup');
BEGIN;
INSERT INTO epoch_child VALUES (6100, 2, 61);
SELECT 1 / 0;
"""


BROKEN_NAMED_RECOVERY_SQL = r"""
\set ON_ERROR_STOP on
SELECT pg_fastfork_epoch_finish('broken-cleanup');
SELECT pg_fastfork_epoch_finish('broken-cleanup');
SELECT pg_fastfork_snapshot('fixture');
SELECT pg_fastfork_restore('fixture');
SELECT pg_fastfork_epoch_start('broken-cleanup', 'fixture');
SELECT pg_fastfork_epoch_join('broken-cleanup');
BEGIN;
INSERT INTO epoch_child VALUES (6101, 2, 62);
COMMIT;
SELECT pg_fastfork_epoch_leave();
SELECT pg_fastfork_epoch_finish('broken-cleanup');
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM epoch_child WHERE id IN (6100, 6101)) THEN
    RAISE EXCEPTION 'broken named epoch cleanup leaked inserted row';
  END IF;
END $$;
"""


def run(
    cmd: list[str],
    *,
    env: dict[str, str],
    input_text: str | None = None,
    capture: bool = True,
    check: bool = True,
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        cmd,
        env=env,
        input=input_text,
        text=True,
        stdout=subprocess.PIPE if capture else None,
        stderr=subprocess.PIPE if capture else None,
        check=check,
    )


class PsqlSession:
    def __init__(self, psql: str, conn_args: list[str], env: dict[str, str], label: str):
        self.label = label
        self.counter = 0
        self.proc = subprocess.Popen(
            [psql, *conn_args, "-d", "bench", "-X", "-qAt", "-v", "ON_ERROR_STOP=1"],
            env=env,
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
        )

    def execute(self, sql: str, label: str) -> str:
        if self.proc.stdin is None or self.proc.stdout is None:
            raise RuntimeError(f"{self.label} psql session is not open")
        if self.proc.poll() is not None:
            raise RuntimeError(f"{self.label} psql session exited before {label}")

        self.counter += 1
        sentinel = f"__fastfork_done_{self.counter}__"
        self.proc.stdin.write(sql)
        if not sql.endswith("\n"):
            self.proc.stdin.write("\n")
        self.proc.stdin.write(f"\\echo {sentinel}\n")
        self.proc.stdin.flush()

        output: list[str] = []
        while True:
            line = self.proc.stdout.readline()
            if line == "":
                if self.proc.poll() is not None:
                    raise RuntimeError(
                        f"{self.label} psql session exited during {label}:\n"
                        + "".join(output)
                    )
                continue
            if sentinel in line:
                return "".join(output)
            output.append(line)

    def close(self) -> None:
        if self.proc.poll() is None and self.proc.stdin is not None:
            try:
                self.proc.stdin.write("\\quit\n")
                self.proc.stdin.flush()
            except BrokenPipeError:
                pass
        try:
            self.proc.wait(timeout=5)
        except subprocess.TimeoutExpired:
            self.proc.terminate()
            try:
                self.proc.wait(timeout=5)
            except subprocess.TimeoutExpired:
                self.proc.kill()


def find_free_port() -> int:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.bind(("127.0.0.1", 0))
        return int(sock.getsockname()[1])


def quote_sql_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def quote_conf_value(value: str) -> str:
    if value in {"on", "off"} or value.isdigit():
        return value
    return "'" + value.replace("'", "''") + "'"


def append_fast_config(data_dir: Path, socket_dir: Path, port: int) -> None:
    with (data_dir / "postgresql.conf").open("a", encoding="utf-8") as conf:
        conf.write("\n# bench/test_fastfork_epoch_rollback.py fast test settings\n")
        for key, value in FAST_SETTINGS.items():
            conf.write(f"{key} = {quote_conf_value(value)}\n")
        conf.write(f"unix_socket_directories = {quote_conf_value(str(socket_dir))}\n")
        conf.write(f"port = {port}\n")


def bin_path(bin_dir: Path, name: str) -> str:
    path = bin_dir / name
    if not path.exists():
        raise SystemExit(f"missing required PostgreSQL binary: {path}")
    return str(path)


def expect_error(
    psql: str,
    conn_args: list[str],
    env: dict[str, str],
    sql: str,
    expected: str,
) -> None:
    proc = run([psql, *conn_args, "-d", "bench"], env=env, input_text=sql, check=False)
    combined = (proc.stdout or "") + (proc.stderr or "")
    if proc.returncode == 0:
        raise RuntimeError(f"expected psql command to fail with {expected!r}")
    if expected not in combined:
        raise RuntimeError(f"expected error containing {expected!r}, got:\n{combined}")


def run_parallel_epoch(psql: str, conn_args: list[str], env: dict[str, str]) -> None:
    cmd = [psql, *conn_args, "-d", "bench", "-v", "ON_ERROR_STOP=1"]
    first = subprocess.Popen(
        [*cmd, "-c", PARALLEL_CONN1_SQL],
        env=env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    try:
        time.sleep(0.2)
        second = run([*cmd, "-c", PARALLEL_CONN2_SQL], env=env, check=False)
        if second.returncode != 0:
            raise RuntimeError(
                "parallel epoch join failed:\n"
                f"{second.stdout or ''}{second.stderr or ''}"
            )

        stdout, stderr = first.communicate(timeout=10)
        if first.returncode != 0:
            raise RuntimeError(
                "parallel epoch leader failed:\n"
                f"{stdout or ''}{stderr or ''}"
            )
    finally:
        if first.poll() is None:
            first.terminate()
            try:
                first.wait(timeout=5)
            except subprocess.TimeoutExpired:
                first.kill()

    run([psql, *conn_args, "-d", "bench"], env=env, input_text=PARALLEL_VERIFY_SQL)


def run_parallel_named_epochs(psql: str, conn_args: list[str], env: dict[str, str]) -> None:
    run([psql, *conn_args, "-d", "bench"], env=env, input_text=CAPTURE_SQL + PARALLEL_NAMED_SETUP_SQL)

    cmd = [psql, *conn_args, "-d", "bench", "-v", "ON_ERROR_STOP=1"]
    first = subprocess.Popen(
        [*cmd, "-c", PARALLEL_NAMED_CONN1_SQL],
        env=env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    try:
        time.sleep(0.2)
        second = run([*cmd, "-c", PARALLEL_NAMED_CONN2_SQL], env=env, check=False)
        if second.returncode != 0:
            raise RuntimeError(
                "parallel named epoch second participant failed:\n"
                f"{second.stdout or ''}{second.stderr or ''}"
            )

        stdout, stderr = first.communicate(timeout=10)
        if first.returncode != 0:
            raise RuntimeError(
                "parallel named epoch first participant failed:\n"
                f"{stdout or ''}{stderr or ''}"
            )
    finally:
        if first.poll() is None:
            first.terminate()
            try:
                first.wait(timeout=5)
            except subprocess.TimeoutExpired:
                first.kill()

    run([psql, *conn_args, "-d", "bench"], env=env, input_text=PARALLEL_NAMED_FINISH_SQL)


def run_parallel_named_finish_while_active(psql: str, conn_args: list[str], env: dict[str, str]) -> None:
    setup_sql = (
        CAPTURE_SQL
        + "\nSELECT pg_fastfork_restore('fixture');\n"
        + "SELECT pg_fastfork_epoch_start('active-a', 'fixture');\n"
        + "SELECT pg_fastfork_epoch_start('active-b', 'fixture');\n"
    )
    run([psql, *conn_args, "-d", "bench"], env=env, input_text=setup_sql)

    cmd = [psql, *conn_args, "-d", "bench", "-v", "ON_ERROR_STOP=1"]
    first = subprocess.Popen(
        [*cmd, "-c", PARALLEL_NAMED_ACTIVE_CONN1_SQL],
        env=env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    try:
        time.sleep(0.2)
        second = run([*cmd, "-c", PARALLEL_NAMED_ACTIVE_CONN2_SQL], env=env, check=False)
        if second.returncode != 0:
            raise RuntimeError(
                "parallel named active second participant failed:\n"
                f"{second.stdout or ''}{second.stderr or ''}"
            )

        finish = run(
            [psql, *conn_args, "-d", "bench"],
            env=env,
            input_text=PARALLEL_NAMED_ACTIVE_FINISH_SQL,
            check=False,
        )
        if finish.returncode != 0:
            raise RuntimeError(
                "parallel named active finish failed:\n"
                f"{finish.stdout or ''}{finish.stderr or ''}"
            )

        stdout, stderr = first.communicate(timeout=10)
        if first.returncode != 0:
            raise RuntimeError(
                "parallel named active first participant failed:\n"
                f"{stdout or ''}{stderr or ''}"
            )
    finally:
        if first.poll() is None:
            first.terminate()
            try:
                first.wait(timeout=5)
            except subprocess.TimeoutExpired:
                first.kill()

    run([psql, *conn_args, "-d", "bench"], env=env, input_text=PARALLEL_NAMED_ACTIVE_FINAL_SQL)


def run_named_epoch_coordinator_connection(psql: str, conn_args: list[str], env: dict[str, str]) -> None:
    coordinator = PsqlSession(psql, conn_args, env, "named epoch coordinator")
    worker = PsqlSession(psql, conn_args, env, "named epoch worker")
    active = None

    try:
        coordinator.execute(CAPTURE_SQL, "capture coordinator fixture")

        for i in range(6):
            epoch = f"coordinator-reuse-{i}"
            coordinator.execute(
                f"SELECT pg_fastfork_epoch_start({quote_sql_literal(epoch)}, 'fixture');\n",
                f"start {epoch}",
            )
            worker.execute(
                f"""
SET ROLE postgres;
SELECT pg_fastfork_epoch_join({quote_sql_literal(epoch)});
RESET ROLE;
BEGIN;
INSERT INTO epoch_child VALUES ({600000 + i}, 2, 44);
ROLLBACK;
SELECT pg_fastfork_epoch_leave();
""",
                f"worker join/leave {epoch}",
            )
            fresh = run(
                [psql, *conn_args, "-d", "bench", "-v", "ON_ERROR_STOP=1", "-c", "SELECT 1;"],
                env=env,
                check=False,
            )
            if fresh.returncode != 0:
                raise RuntimeError(
                    "fresh connection failed while coordinator-owned epoch existed:\n"
                    f"{fresh.stdout or ''}{fresh.stderr or ''}"
                )
            coordinator.execute(
                f"""
SELECT pg_fastfork_epoch_finish({quote_sql_literal(epoch)});
SELECT pg_fastfork_epoch_finish({quote_sql_literal(epoch)});
""",
                f"finish {epoch}",
            )

        coordinator.execute(
            "SELECT pg_fastfork_epoch_start('coordinator-active-a', 'fixture');\n",
            "start coordinator-active-a",
        )
        active = subprocess.Popen(
            [
                psql,
                *conn_args,
                "-d",
                "bench",
                "-X",
                "-qAt",
                "-v",
                "ON_ERROR_STOP=1",
                "-c",
                """
SET ROLE postgres;
SELECT pg_fastfork_epoch_join('coordinator-active-a');
RESET ROLE;
BEGIN;
INSERT INTO epoch_child VALUES (600100, 2, 45);
SELECT pg_sleep(1.0);
ROLLBACK;
SELECT pg_fastfork_epoch_leave();
""",
            ],
            env=env,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        time.sleep(0.2)

        fresh = run(
            [psql, *conn_args, "-d", "bench", "-v", "ON_ERROR_STOP=1", "-c", "SELECT 1;"],
            env=env,
            check=False,
        )
        if fresh.returncode != 0:
            raise RuntimeError(
                "fresh connection failed while another named epoch had an active participant:\n"
                f"{fresh.stdout or ''}{fresh.stderr or ''}"
            )

        coordinator.execute(
            "SELECT pg_fastfork_epoch_start('coordinator-active-b', 'fixture');\n",
            "start coordinator-active-b while coordinator-active-a is active",
        )
        worker.execute(
            """
SET ROLE postgres;
SELECT pg_fastfork_epoch_join('coordinator-active-b');
RESET ROLE;
BEGIN;
INSERT INTO epoch_child VALUES (600101, 3, 46);
COMMIT;
SELECT pg_fastfork_epoch_leave();
""",
            "worker join/leave coordinator-active-b",
        )
        coordinator.execute(
            "SELECT pg_fastfork_epoch_finish('coordinator-active-b');\n",
            "finish coordinator-active-b while coordinator-active-a is active",
        )

        stdout, stderr = active.communicate(timeout=10)
        if active.returncode != 0:
            raise RuntimeError(
                "active named epoch worker failed:\n"
                f"{stdout or ''}{stderr or ''}"
            )
        active = None

        coordinator.execute(
            "SELECT pg_fastfork_epoch_finish('coordinator-active-a');\n",
            "finish coordinator-active-a",
        )

        run(
            [psql, *conn_args, "-d", "bench"],
            env=env,
            input_text=r"""
\set ON_ERROR_STOP on
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM epoch_child WHERE id BETWEEN 600000 AND 600101) THEN
    RAISE EXCEPTION 'coordinator named epoch cleanup leaked inserted row';
  END IF;
END $$;
""",
        )
    finally:
        if active is not None and active.poll() is None:
            active.terminate()
            try:
                active.wait(timeout=5)
            except subprocess.TimeoutExpired:
                active.kill()
        worker.close()
        coordinator.close()


def run_named_session_visibility(psql: str, conn_args: list[str], env: dict[str, str]) -> None:
    run([psql, *conn_args, "-d", "bench"], env=env, input_text=CAPTURE_SQL + NAMED_SESSION_VISIBILITY_SETUP_SQL)

    cmd = [psql, *conn_args, "-d", "bench", "-v", "ON_ERROR_STOP=1"]
    reader = subprocess.Popen(
        [*cmd, "-c", NAMED_SESSION_VISIBILITY_READER_SQL],
        env=env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    try:
        time.sleep(0.2)
        writer = run([*cmd, "-c", NAMED_SESSION_VISIBILITY_WRITER_SQL], env=env, check=False)
        if writer.returncode != 0:
            raise RuntimeError(
                "named epoch visibility writer failed:\n"
                f"{writer.stdout or ''}{writer.stderr or ''}"
            )

        stdout, stderr = reader.communicate(timeout=10)
        if reader.returncode != 0:
            raise RuntimeError(
                "named epoch visibility reader failed:\n"
                f"{stdout or ''}{stderr or ''}"
            )
    finally:
        if reader.poll() is None:
            reader.terminate()
            try:
                reader.wait(timeout=5)
            except subprocess.TimeoutExpired:
                reader.kill()

    run([psql, *conn_args, "-d", "bench"], env=env, input_text=NAMED_SESSION_VISIBILITY_FINISH_SQL)


def run_named_epoch_cleanup_after_error(psql: str, conn_args: list[str], env: dict[str, str]) -> None:
    setup_sql = (
        CAPTURE_SQL
        + "\nSELECT pg_fastfork_restore('fixture');\n"
        + "SELECT pg_fastfork_epoch_start('broken-cleanup', 'fixture');\n"
    )
    run([psql, *conn_args, "-d", "bench"], env=env, input_text=setup_sql)

    failed = run(
        [psql, *conn_args, "-d", "bench", "-v", "ON_ERROR_STOP=1", "-c", BROKEN_NAMED_CONN_SQL],
        env=env,
        check=False,
    )
    combined = (failed.stdout or "") + (failed.stderr or "")
    if failed.returncode == 0:
        raise RuntimeError("expected broken named epoch participant to fail")
    if "division by zero" not in combined:
        raise RuntimeError(
            "expected broken named epoch participant to fail with division by zero:\n"
            f"{combined}"
        )

    run([psql, *conn_args, "-d", "bench"], env=env, input_text=BROKEN_NAMED_RECOVERY_SQL)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bin", required=True, type=Path, help="PostgreSQL install bin directory")
    parser.add_argument("--keep-workdir", action="store_true", help="do not delete the disposable cluster")
    args = parser.parse_args()

    bin_dir = args.bin.resolve()
    initdb = bin_path(bin_dir, "initdb")
    pg_ctl = bin_path(bin_dir, "pg_ctl")
    createdb = bin_path(bin_dir, "createdb")
    psql = bin_path(bin_dir, "psql")

    env = os.environ.copy()
    env["PATH"] = f"{bin_dir}{os.pathsep}{env.get('PATH', '')}"
    env.setdefault("LC_ALL", "C")

    workdir = Path(tempfile.mkdtemp(prefix="fastfork-epoch-"))
    data_dir = workdir / "data"
    socket_dir = workdir / "socket"
    log_file = workdir / "postgres.log"
    socket_dir.mkdir(parents=True, exist_ok=True)
    port = find_free_port()
    started = False

    try:
        run([initdb, "-D", str(data_dir), "--no-sync", "-A", "trust", "-U", "postgres"], env=env)
        append_fast_config(data_dir, socket_dir, port)
        run([pg_ctl, "-D", str(data_dir), "-l", str(log_file), "-w", "start"], env=env)
        started = True

        conn_args = ["-h", str(socket_dir), "-p", str(port), "-U", "postgres"]
        run([createdb, *conn_args, "bench"], env=env)
        run([psql, *conn_args, "-d", "bench"], env=env, input_text=SETUP_SQL)
        run([psql, *conn_args, "-d", "bench"], env=env, input_text=CAPTURE_SQL + DML_SQL)
        run([psql, *conn_args, "-d", "bench"], env=env, input_text=CAPTURE_SQL + SESSION_SQL)
        run([psql, *conn_args, "-d", "bench"], env=env, input_text=CAPTURE_SQL + NAMED_SQL)
        run_parallel_named_epochs(psql, conn_args, env)
        run_parallel_named_finish_while_active(psql, conn_args, env)
        run_named_epoch_coordinator_connection(psql, conn_args, env)
        run_named_session_visibility(psql, conn_args, env)
        run_named_epoch_cleanup_after_error(psql, conn_args, env)
        run([psql, *conn_args, "-d", "bench"], env=env, input_text=CAPTURE_SQL + REUSED_BACKEND_NAMED_SQL)
        run([psql, *conn_args, "-d", "bench"], env=env, input_text=CAPTURE_SQL + "SELECT pg_fastfork_restore('fixture');\n")
        run_parallel_epoch(psql, conn_args, env)
        expect_error(
            psql,
            conn_args,
            env,
            CAPTURE_SQL + COMMIT_SQL,
            "fast-fork epoch transactions are rollback-only",
        )
        expect_error(
            psql,
            conn_args,
            env,
            CAPTURE_SQL + UNSUPPORTED_DDL_SQL,
            "DDL is not supported for this object type in fast-fork epoch transactions",
        )
        expect_error(
            psql,
            conn_args,
            env,
            CAPTURE_SQL + PREPARE_SQL,
            "prepared transactions are not supported in fast-fork epoch transactions",
        )
        run([psql, *conn_args, "-d", "bench"], env=env, input_text=CAPTURE_SQL + DDL_SQL)
        run([psql, *conn_args, "-d", "bench"], env=env, input_text=CAPTURE_SQL + DML_SQL)
        print("fast-fork epoch rollback smoke test passed")
        return 0
    except (RuntimeError, subprocess.CalledProcessError) as exc:
        if isinstance(exc, subprocess.CalledProcessError):
            if exc.stdout:
                print(exc.stdout, file=sys.stderr)
            if exc.stderr:
                print(exc.stderr, file=sys.stderr)
        else:
            print(str(exc), file=sys.stderr)
        print(f"cluster log: {log_file}", file=sys.stderr)
        return 1
    finally:
        if started:
            subprocess.run(
                [pg_ctl, "-D", str(data_dir), "-m", "fast", "-w", "stop"],
                env=env,
                text=True,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                check=False,
            )
        if args.keep_workdir:
            print(f"kept workdir: {workdir}", file=sys.stderr)
        else:
            shutil.rmtree(workdir, ignore_errors=True)


if __name__ == "__main__":
    raise SystemExit(main())
