#!/usr/bin/env python3
"""Stress-test fast-fork named epochs against an installed build."""

from __future__ import annotations

import argparse
import os
import shutil
import socket
import subprocess
import sys
import tempfile
import time
from pathlib import Path


FAST_SETTINGS = {
    "listen_addresses": "",
    "fsync": "off",
    "synchronous_commit": "off",
    "full_page_writes": "off",
    "wal_level": "minimal",
    "archive_mode": "off",
    "max_wal_senders": "0",
    "max_replication_slots": "0",
    "autovacuum": "off",
    "track_counts": "off",
    "jit": "off",
    "max_connections": "64",
}

FIXTURE_PARENTS = 400
FIXTURE_CHILDREN_PER_PARENT = 6
FIXTURE_EVENTS_PER_PARENT = 2
SEQUENTIAL_EPOCHS = 12
SEQUENTIAL_WORKERS = 3
PARALLEL_EPOCHS = 4
PARALLEL_WORKERS = 2
PARENT_INSERTS_PER_WORKER = 48
CHILDREN_PER_INSERTED_PARENT = 12

CLIENT_FAILURE_PATTERNS = (
    "memory storage manager page arena is full",
    "server closed the connection unexpectedly",
    "connection to server was lost",
    "could not send data to server",
)

LOG_FAILURE_PATTERNS = (
    "memory storage manager page arena is full",
    "unexpected EOF",
    "server process (PID ",
    "terminating connection because of crash",
    "terminating connection because of unexpected",
    "PANIC:",
)

SETUP_SQL = rf"""
CREATE TABLE app_tenant (
    id integer PRIMARY KEY,
    name text NOT NULL UNIQUE
);

CREATE TABLE app_parent (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id integer NOT NULL REFERENCES app_tenant(id),
    natural_key text NOT NULL UNIQUE,
    status text NOT NULL DEFAULT 'fixture',
    payload text NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX app_parent_tenant_status_idx
    ON app_parent (tenant_id, status, id);

CREATE TABLE app_child (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id bigint NOT NULL REFERENCES app_parent(id) ON DELETE CASCADE,
    line_no integer NOT NULL,
    amount integer NOT NULL,
    payload text NOT NULL,
    UNIQUE(parent_id, line_no)
);

CREATE INDEX app_child_parent_amount_idx
    ON app_child (parent_id, amount);

CREATE TABLE app_event (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id bigint NOT NULL REFERENCES app_parent(id),
    event_type text NOT NULL,
    seq integer NOT NULL,
    payload text NOT NULL
);

CREATE INDEX app_event_parent_seq_idx
    ON app_event (parent_id, seq);

INSERT INTO app_tenant(id, name)
SELECT g, 'tenant-' || g::text
FROM generate_series(1, 8) AS g;

INSERT INTO app_parent(tenant_id, natural_key, status, payload)
SELECT ((g - 1) % 8) + 1,
       'fixture-parent-' || g::text,
       'fixture',
       repeat(md5(g::text), 8)
FROM generate_series(1, {FIXTURE_PARENTS}) AS g;

INSERT INTO app_child(parent_id, line_no, amount, payload)
SELECT p.id,
       line_no,
       (p.id + line_no) % 100,
       repeat(md5((p.id * 100 + line_no)::text), 6)
FROM app_parent AS p
CROSS JOIN generate_series(1, {FIXTURE_CHILDREN_PER_PARENT}) AS line_no;

INSERT INTO app_event(parent_id, event_type, seq, payload)
SELECT p.id,
       'fixture',
       seq,
       repeat(md5((p.id * 10 + seq)::text), 5)
FROM app_parent AS p
CROSS JOIN generate_series(1, {FIXTURE_EVENTS_PER_PARENT}) AS seq;

ANALYZE app_tenant;
ANALYZE app_parent;
ANALYZE app_child;
ANALYZE app_event;
SELECT pg_fastfork_snapshot('fixture');
"""

VERIFY_FIXTURE_SQL = rf"""
DO $$
BEGIN
  IF (SELECT count(*) FROM app_parent) <> {FIXTURE_PARENTS} THEN
    RAISE EXCEPTION 'named epoch stress leaked parent rows';
  END IF;

  IF (SELECT count(*) FROM app_child) <>
     {FIXTURE_PARENTS * FIXTURE_CHILDREN_PER_PARENT} THEN
    RAISE EXCEPTION 'named epoch stress leaked child rows';
  END IF;

  IF (SELECT count(*) FROM app_event) <>
     {FIXTURE_PARENTS * FIXTURE_EVENTS_PER_PARENT} THEN
    RAISE EXCEPTION 'named epoch stress leaked event rows';
  END IF;

  IF EXISTS (
      SELECT 1
      FROM app_parent
      WHERE status <> 'fixture'
         OR natural_key LIKE 'epoch-%'
         OR natural_key LIKE 'failure-%'
         OR natural_key LIKE 'parallel-%'
  ) THEN
    RAISE EXCEPTION 'named epoch stress leaked mutated parent state';
  END IF;
END $$;

SET enable_seqscan = off;
SELECT p.id, count(c.id), count(e.id)
FROM app_parent AS p
JOIN app_child AS c ON c.parent_id = p.id
JOIN app_event AS e ON e.parent_id = p.id
WHERE p.tenant_id = 3
  AND p.status = 'fixture'
  AND c.amount BETWEEN 10 AND 80
GROUP BY p.id
ORDER BY p.id
LIMIT 5;
RESET enable_seqscan;
"""


def run(
    cmd: list[str],
    *,
    env: dict[str, str],
    input_text: str | None = None,
    capture: bool = True,
    check: bool = True,
) -> subprocess.CompletedProcess[str]:
    proc = subprocess.run(
        cmd,
        env=env,
        input=input_text,
        text=True,
        stdout=subprocess.PIPE if capture else None,
        stderr=subprocess.PIPE if capture else None,
        check=False,
    )
    if check and proc.returncode != 0:
        raise subprocess.CalledProcessError(
            proc.returncode,
            cmd,
            output=proc.stdout,
            stderr=proc.stderr,
        )
    return proc


def find_free_port() -> int:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.bind(("127.0.0.1", 0))
        return int(sock.getsockname()[1])


def quote_conf_value(value: str) -> str:
    if value in {"on", "off"} or value.isdigit():
        return value
    return "'" + value.replace("'", "''") + "'"


def quote_sql(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def append_fast_config(data_dir: Path, socket_dir: Path, port: int) -> None:
    with (data_dir / "postgresql.conf").open("a", encoding="utf-8") as conf:
        conf.write("\n# bench/test_fastfork_named_epoch_stress.py settings\n")
        for key, value in FAST_SETTINGS.items():
            conf.write(f"{key} = {quote_conf_value(value)}\n")
        conf.write(f"unix_socket_directories = {quote_conf_value(str(socket_dir))}\n")
        conf.write(f"port = {port}\n")


def bin_path(bin_dir: Path, name: str) -> str:
    path = bin_dir / name
    if not path.exists():
        raise SystemExit(f"missing required PostgreSQL binary: {path}")
    return str(path)


def assert_no_client_disconnect(label: str, output: str) -> None:
    lowered = output.lower()
    for pattern in CLIENT_FAILURE_PATTERNS:
        if pattern in lowered:
            raise RuntimeError(f"{label} saw unexpected connection failure:\n{output}")


def assert_no_bad_log(log_file: Path) -> None:
    if not log_file.exists():
        return

    text = log_file.read_text(encoding="utf-8", errors="replace")
    lowered = text.lower()
    for pattern in LOG_FAILURE_PATTERNS:
        if pattern.lower() in lowered:
            raise RuntimeError(
                f"cluster log contains unexpected failure pattern {pattern!r}:\n"
                f"{tail(text)}"
            )


def tail(text: str, lines: int = 80) -> str:
    return "\n".join(text.splitlines()[-lines:])


def psql_cmd(psql: str, conn_args: list[str]) -> list[str]:
    return [psql, *conn_args, "-d", "bench", "-v", "ON_ERROR_STOP=1"]


def run_psql(
    psql: str,
    conn_args: list[str],
    env: dict[str, str],
    sql: str,
    *,
    label: str,
    check: bool = True,
) -> subprocess.CompletedProcess[str]:
    proc = run(
        psql_cmd(psql, conn_args),
        env=env,
        input_text="\\set ON_ERROR_STOP on\n" + sql,
        check=False,
    )
    combined = (proc.stdout or "") + (proc.stderr or "")
    assert_no_client_disconnect(label, combined)
    if check and proc.returncode != 0:
        raise RuntimeError(f"{label} failed:\n{combined}")
    return proc


def expect_psql_error(
    psql: str,
    conn_args: list[str],
    env: dict[str, str],
    sql: str,
    *,
    label: str,
    expected: str,
) -> None:
    proc = run_psql(psql, conn_args, env, sql, label=label, check=False)
    combined = (proc.stdout or "") + (proc.stderr or "")
    if proc.returncode == 0:
        raise RuntimeError(f"{label} unexpectedly succeeded")
    if expected not in combined:
        raise RuntimeError(f"{label} did not contain {expected!r}:\n{combined}")


def start_epochs(
    psql: str,
    conn_args: list[str],
    env: dict[str, str],
    names: list[str],
) -> None:
    start_sql = "SELECT pg_fastfork_snapshot('fixture');\n"
    start_sql += "\n".join(
        f"SELECT pg_fastfork_epoch_start({quote_sql(name)}, 'fixture');"
        for name in names
    )
    run_psql(psql, conn_args, env, start_sql, label=f"start epochs {names}")


def finish_epoch(
    psql: str,
    conn_args: list[str],
    env: dict[str, str],
    name: str,
) -> None:
    finish_sql = (
        f"SELECT pg_fastfork_epoch_finish({quote_sql(name)});\n"
        f"SELECT pg_fastfork_epoch_finish({quote_sql(name)});\n"
    )
    last_output = ""
    for _ in range(20):
        proc = run_psql(
            psql,
            conn_args,
            env,
            finish_sql,
            label=f"finish epoch {name}",
            check=False,
        )
        last_output = (proc.stdout or "") + (proc.stderr or "")
        if proc.returncode == 0:
            return
        if "still has active participants" not in last_output:
            break
        time.sleep(0.1)
    raise RuntimeError(f"finish epoch {name} failed:\n{last_output}")


def worker_sql(
    epoch: str,
    suite_id: int,
    worker_id: int,
    *,
    prefix: str,
    fail_after_commit: bool = False,
) -> str:
    parent_start = ((suite_id * 37 + worker_id * 53) % (FIXTURE_PARENTS - 80)) + 1
    parent_end = parent_start + 79
    status = f"epoch-{suite_id}-{worker_id}"
    key_prefix = f"{prefix}-{suite_id}-{worker_id}"
    fail_sql = "SELECT 1 / 0;\n" if fail_after_commit else ""

    return f"""
SELECT pg_fastfork_epoch_join({quote_sql(epoch)});
SET enable_seqscan = off;
BEGIN;
WITH touched AS (
    UPDATE app_parent
    SET status = {quote_sql(status)},
        payload = payload || {quote_sql(f":{status}")},
        updated_at = clock_timestamp()
    WHERE id BETWEEN {parent_start} AND {parent_end}
    RETURNING id
), removed AS (
    DELETE FROM app_child AS c
    USING touched AS t
    WHERE c.parent_id = t.id
      AND c.line_no % {SEQUENTIAL_WORKERS + PARALLEL_WORKERS} = {worker_id}
    RETURNING c.id
), new_parents AS (
    INSERT INTO app_parent(tenant_id, natural_key, status, payload)
    SELECT ((g - 1) % 8) + 1,
           {quote_sql(key_prefix + "-parent-")} || g::text,
           'new',
           repeat(md5(({suite_id} * 100000 + {worker_id} * 1000 + g)::text), 12)
    FROM generate_series(1, {PARENT_INSERTS_PER_WORKER}) AS g
    RETURNING id
), new_children AS (
    INSERT INTO app_child(parent_id, line_no, amount, payload)
    SELECT p.id,
           line_no,
           ({suite_id} + {worker_id} + line_no) % 100,
           repeat(md5((p.id * 100 + line_no)::text), 8)
    FROM new_parents AS p
    CROSS JOIN generate_series(1, {CHILDREN_PER_INSERTED_PARENT}) AS line_no
    RETURNING id, parent_id
)
INSERT INTO app_event(parent_id, event_type, seq, payload)
SELECT parent_id,
       'child-created',
       row_number() OVER (),
       repeat(md5(id::text), 6)
FROM new_children
WHERE id % 3 = 0;

SAVEPOINT transient_application_work;
UPDATE app_parent
SET payload = payload || ':transient'
WHERE natural_key LIKE {quote_sql(key_prefix + "-parent-%")};
ROLLBACK TO SAVEPOINT transient_application_work;

SELECT p.id, count(c.id), coalesce(sum(c.amount), 0)
FROM app_parent AS p
JOIN app_child AS c ON c.parent_id = p.id
WHERE p.id BETWEEN {parent_start} AND {parent_end}
GROUP BY p.id
ORDER BY p.id
LIMIT 8;
COMMIT;

SELECT 1 / CASE
    WHEN (SELECT count(*) FROM app_parent
          WHERE natural_key LIKE {quote_sql(key_prefix + "-parent-%")}) =
         {PARENT_INSERTS_PER_WORKER}
    THEN 1 ELSE 0 END;
SELECT 1 / CASE
    WHEN (SELECT count(*) FROM app_child AS c
          JOIN app_parent AS p ON p.id = c.parent_id
          WHERE p.natural_key LIKE {quote_sql(key_prefix + "-parent-%")}) =
         {PARENT_INSERTS_PER_WORKER * CHILDREN_PER_INSERTED_PARENT}
    THEN 1 ELSE 0 END;
{fail_sql}SELECT pg_fastfork_epoch_leave();
"""


def run_workers(
    psql: str,
    conn_args: list[str],
    env: dict[str, str],
    workers: list[tuple[str, str]],
    *,
    timeout: float = 60.0,
) -> None:
    cmd = psql_cmd(psql, conn_args)
    processes: list[tuple[str, subprocess.Popen[str]]] = []
    try:
        for label, sql in workers:
            processes.append(
                (
                    label,
                    subprocess.Popen(
                        [*cmd, "-c", sql],
                        env=env,
                        text=True,
                        stdout=subprocess.PIPE,
                        stderr=subprocess.PIPE,
                    ),
                )
            )

        deadline = time.monotonic() + timeout
        for label, proc in processes:
            remaining = max(1.0, deadline - time.monotonic())
            stdout, stderr = proc.communicate(timeout=remaining)
            combined = (stdout or "") + (stderr or "")
            assert_no_client_disconnect(label, combined)
            if proc.returncode != 0:
                raise RuntimeError(f"{label} failed:\n{combined}")
    finally:
        for _, proc in processes:
            if proc.poll() is None:
                proc.terminate()
                try:
                    proc.wait(timeout=5)
                except subprocess.TimeoutExpired:
                    proc.kill()


def run_sequential_suite(psql: str, conn_args: list[str], env: dict[str, str]) -> None:
    for epoch_index in range(SEQUENTIAL_EPOCHS):
        epoch = f"stress-seq-{epoch_index}"
        start_epochs(psql, conn_args, env, [epoch])
        run_workers(
            psql,
            conn_args,
            env,
            [
                (
                    f"{epoch} worker {worker_id}",
                    worker_sql(epoch, 100, worker_id, prefix="epoch"),
                )
                for worker_id in range(SEQUENTIAL_WORKERS)
            ],
        )
        run_psql(
            psql,
            conn_args,
            env,
            "SELECT pg_fastfork_epoch_status();",
            label=f"{epoch} status",
        )
        finish_epoch(psql, conn_args, env, epoch)
        run_psql(psql, conn_args, env, VERIFY_FIXTURE_SQL, label=f"{epoch} verify")


def run_parallel_suite(psql: str, conn_args: list[str], env: dict[str, str]) -> None:
    epochs = [f"stress-parallel-{index}" for index in range(PARALLEL_EPOCHS)]
    start_epochs(psql, conn_args, env, epochs)
    run_workers(
        psql,
        conn_args,
        env,
        [
            (
                f"{epoch} worker {worker_id}",
                worker_sql(epoch, 900, worker_id, prefix="parallel"),
            )
            for epoch in epochs
            for worker_id in range(PARALLEL_WORKERS)
        ],
        timeout=90.0,
    )
    for epoch in epochs:
        finish_epoch(psql, conn_args, env, epoch)
    run_psql(psql, conn_args, env, VERIFY_FIXTURE_SQL, label="parallel suite verify")


def run_failed_epoch_recovery(psql: str, conn_args: list[str], env: dict[str, str]) -> None:
    failed_epoch = "stress-failure"
    start_epochs(psql, conn_args, env, [failed_epoch])
    expect_psql_error(
        psql,
        conn_args,
        env,
        worker_sql(
            failed_epoch,
            777,
            0,
            prefix="failure",
            fail_after_commit=True,
        ),
        label="failed epoch worker",
        expected="division by zero",
    )
    finish_epoch(psql, conn_args, env, failed_epoch)
    run_psql(psql, conn_args, env, VERIFY_FIXTURE_SQL, label="failed epoch verify")

    after_epoch = "stress-after-failure"
    start_epochs(psql, conn_args, env, [after_epoch])
    run_workers(
        psql,
        conn_args,
        env,
        [
            (
                "after-failure worker",
                worker_sql(after_epoch, 777, 0, prefix="failure"),
            )
        ],
    )
    finish_epoch(psql, conn_args, env, after_epoch)
    run_psql(psql, conn_args, env, VERIFY_FIXTURE_SQL, label="after failure verify")


def run_join_failure_cleanup(psql: str, conn_args: list[str], env: dict[str, str]) -> None:
    epochs = ["stress-join-failure-a", "stress-join-failure-b"]
    start_epochs(psql, conn_args, env, epochs)
    expect_psql_error(
        psql,
        conn_args,
        env,
        f"""
SELECT pg_fastfork_epoch_join({quote_sql(epochs[0])});
SELECT pg_fastfork_epoch_join({quote_sql(epochs[1])});
""",
        label="joined backend second join failure",
        expected="backend is already joined to fast-fork epoch",
    )
    for epoch in epochs:
        finish_epoch(psql, conn_args, env, epoch)

    run_psql(
        psql,
        conn_args,
        env,
        "SELECT pg_fastfork_epoch_leave();",
        label="unjoined leave cleanup",
    )
    finish_epoch(psql, conn_args, env, "stress-missing-epoch")
    run_psql(psql, conn_args, env, VERIFY_FIXTURE_SQL, label="join cleanup verify")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bin", required=True, type=Path, help="PostgreSQL install bin directory")
    parser.add_argument("--keep-workdir", action="store_true", help="do not delete the disposable cluster")
    args = parser.parse_args()

    bin_dir = args.bin.resolve()
    initdb = bin_path(bin_dir, "initdb")
    pg_ctl = bin_path(bin_dir, "pg_ctl")
    createdb = bin_path(bin_dir, "createdb")
    psql = bin_path(bin_dir, "psql")

    env = os.environ.copy()
    env["PATH"] = f"{bin_dir}{os.pathsep}{env.get('PATH', '')}"
    env.setdefault("LC_ALL", "C")

    workdir = Path(tempfile.mkdtemp(prefix="ffne-", dir="/tmp"))
    data_dir = workdir / "data"
    socket_dir = workdir / "socket"
    log_file = workdir / "postgres.log"
    socket_dir.mkdir(parents=True, exist_ok=True)
    port = find_free_port()
    started = False

    try:
        run([initdb, "-D", str(data_dir), "--no-sync", "-A", "trust", "-U", "postgres"], env=env)
        append_fast_config(data_dir, socket_dir, port)
        run([pg_ctl, "-D", str(data_dir), "-l", str(log_file), "-w", "start"], env=env)
        started = True

        conn_args = ["-h", str(socket_dir), "-p", str(port), "-U", "postgres"]
        run([createdb, *conn_args, "bench"], env=env)
        run_psql(psql, conn_args, env, SETUP_SQL, label="fixture setup")
        run_sequential_suite(psql, conn_args, env)
        run_parallel_suite(psql, conn_args, env)
        run_failed_epoch_recovery(psql, conn_args, env)
        run_join_failure_cleanup(psql, conn_args, env)
        assert_no_bad_log(log_file)
        print("fast-fork named epoch stress test passed")
        return 0
    except (RuntimeError, subprocess.CalledProcessError) as exc:
        if isinstance(exc, subprocess.CalledProcessError):
            if exc.stdout:
                print(exc.stdout, file=sys.stderr)
            if exc.stderr:
                print(exc.stderr, file=sys.stderr)
        else:
            print(str(exc), file=sys.stderr)
        print(f"cluster log: {log_file}", file=sys.stderr)
        return 1
    finally:
        if started:
            subprocess.run(
                [pg_ctl, "-D", str(data_dir), "-m", "fast", "-w", "stop"],
                env=env,
                text=True,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                check=False,
            )
        if args.keep_workdir:
            print(f"kept workdir: {workdir}", file=sys.stderr)
        else:
            shutil.rmtree(workdir, ignore_errors=True)


if __name__ == "__main__":
    raise SystemExit(main())
