DROP TABLE IF EXISTS fastpg_reg_txn;
CREATE TABLE fastpg_reg_txn (id int NOT NULL, amount int);
INSERT INTO fastpg_reg_txn VALUES (1, 10);
BEGIN;
INSERT INTO fastpg_reg_txn VALUES (2, 20);
UPDATE fastpg_reg_txn SET amount = amount + 5 WHERE id = 1;
ROLLBACK;
SELECT 'txn_after_rollback', id, amount FROM fastpg_reg_txn;
BEGIN;
INSERT INTO fastpg_reg_txn VALUES (3, 30);
COMMIT;
SELECT 'txn_after_commit', id, amount FROM fastpg_reg_txn;
DROP TABLE fastpg_reg_txn;
