DROP TABLE IF EXISTS fastpg_reg_pk;
CREATE TABLE fastpg_reg_pk (id int NOT NULL, code text, amount int);
INSERT INTO fastpg_reg_pk VALUES (1, 'alpha', 10);
INSERT INTO fastpg_reg_pk VALUES (2, 'beta', 20);
ALTER TABLE fastpg_reg_pk ADD PRIMARY KEY (id);
SELECT 'pk_lookup_before', code, amount FROM fastpg_reg_pk WHERE id = 2;
UPDATE fastpg_reg_pk SET amount = amount + 5 WHERE id = 2;
SELECT 'pk_lookup_after', code, amount FROM fastpg_reg_pk WHERE id = 2;
SELECT 'class_table', relkind FROM pg_catalog.pg_class WHERE oid = 'fastpg_reg_pk'::pg_catalog.regclass;
SELECT 'class_index', relkind FROM pg_catalog.pg_class WHERE oid = 'fastpg_reg_pk_pkey'::pg_catalog.regclass;
DROP TABLE fastpg_reg_pk;
