DROP TABLE IF EXISTS fastpg_reg_join_a;
DROP TABLE IF EXISTS fastpg_reg_join_b;
CREATE TABLE fastpg_reg_join_a (id int NOT NULL, amount int);
CREATE TABLE fastpg_reg_join_b (id int NOT NULL, label text);
INSERT INTO fastpg_reg_join_a VALUES (1, 10);
INSERT INTO fastpg_reg_join_a VALUES (2, 20);
INSERT INTO fastpg_reg_join_b VALUES (1, 'one');
INSERT INTO fastpg_reg_join_b VALUES (2, 'two');
SELECT 'join_match', a.id, a.amount, b.label FROM fastpg_reg_join_a a JOIN fastpg_reg_join_b b ON b.id = a.id;
DROP TABLE fastpg_reg_join_a;
DROP TABLE fastpg_reg_join_b;
